### ISSUE TITLE
Is it not better to use Vite then webpack?

### ISSUE THREAD

**Issue by TouqeerH** [script-genies/react-skeleton-app#4]
After exploring various front-end build tools, I highly recommend considering `Vite` over `Webpack` for your next project. Vite is a modern build tool that is designed to optimize the development experience and provide faster builds than `Webpack`.

Here are some advantages of using `Vite` over `Webpack`:

- Faster development experience
- Faster builds
- Simplified configuration.
- Better performance
- Active community

Overall, `Vite` offers a more modern and optimized approach to building front-end applications. While `Webpack` is still a powerful tool, I highly recommend considering `Vite` for your next project.

**Comment by misbahkhalilaz** [comment]
I really appreciate your suggestion mate, I would take a look into this, I was also considering other alternatives like SWC, which would be a nice update.
